export interface Weapon {
  id: string;
  name: string;
  picture: string;
}

export const WEAPONS: Weapon[] = [
  { id: '357_magnum', name: '357 Magnum', picture: './weapons/357_magnum.png' },
  { id: '509', name: '509', picture: './weapons/509.png' },
  { id: '590m', name: '590M', picture: './weapons/590m.png' },
  { id: '870cqb', name: '870CQB', picture: './weapons/870cqb.png' },
  { id: 'arn-180', name: 'Arn 180', picture: './weapons/arn-180.png' },
  { id: 'arwc', name: 'ARWC', picture: './weapons/arwc.png' },
  { id: 'b92x', name: 'B92X', picture: './weapons/b92x.png' },
  { id: 'b1301', name: 'B1301', picture: './weapons/b1301.png' },
  { id: 'beanbag_shotgun', name: 'Beanbag Shotgun', picture: './weapons/beanbag_shotgun.png' },
  { id: 'dm4pdw', name: 'DM4PDW', picture: './weapons/dm4pdw.png' },
  { id: 'f90', name: 'F90', picture: './weapons/f90.png' },
  { id: 'fiveseven', name: 'Fiveseven', picture: './weapons/fiveseven.png' },
  { id: 'g3a3', name: 'G3A3', picture: './weapons/g3a3.png' },
  { id: 'g19', name: 'G19', picture: './weapons/g19.png' },
  { id: 'g36c', name: 'G36C', picture: './weapons/g36c.png' },
  { id: 'ga51', name: 'GA51', picture: './weapons/ga51.png' },
  { id: 'ga416', name: 'GA416', picture: './weapons/ga416.png' },
  { id: 'lvar', name: 'LVAR', picture: './weapons/lvar.png' },
  { id: 'm11_compact', name: 'M11 Compact', picture: './weapons/m11_compact.png' },
  { id: 'm14s-16', name: 'M14S 16', picture: './weapons/m14s-16.png' },
  { id: 'm32a1_flash', name: 'M32A1 Flash', picture: './weapons/m32a1_flash.png' },
  { id: 'm32a1_gas', name: 'M32A1 Gas', picture: './weapons/m32a1_gas.png' },
  { id: 'm45a1', name: 'M45A1', picture: './weapons/m45a1.png' },
  { id: 'm1014', name: 'M1014', picture: './weapons/m1014.png' },
  { id: 'mcx', name: 'MCX', picture: './weapons/mcx.png' },
  { id: 'mk-v', name: 'MK V', picture: './weapons/mk-v.png' },
  { id: 'mk16', name: 'MK16', picture: './weapons/mk16.png' },
  { id: 'mk17', name: 'MK17', picture: './weapons/mk17.png' },
  { id: 'mk18', name: 'MK18', picture: './weapons/mk18.png' },
  { id: 'mp5_10mm', name: 'MP5 10mm', picture: './weapons/mp5_10mm.png' },
  { id: 'mp5a2', name: 'MP5A2', picture: './weapons/mp5a2.png' },
  { id: 'mp5a3', name: 'MP5A3', picture: './weapons/mp5a3.png' },
  { id: 'mp5sd6', name: 'MP5SD6', picture: './weapons/mp5sd6.png' },
  { id: 'mp7', name: 'MP7', picture: './weapons/mp7.png' },
  { id: 'mp9', name: 'MP9', picture: './weapons/mp9.png' },
  { id: 'mpx', name: 'MPX', picture: './weapons/mpx.png' },
  { id: 'p90', name: 'P90', picture: './weapons/p90.png' },
  { id: 'raider_x_p320', name: 'Raider X P320', picture: './weapons/raider_x_p320.png' },
  { id: 'sa-58_osw', name: 'SA 58 OSW', picture: './weapons/sa-58_osw.png' },
  { id: 'slr47', name: 'SLR47', picture: './weapons/slr47.png' },
  { id: 'spc9', name: 'SPC9', picture: './weapons/spc9.png' },
  { id: 'sr-16', name: 'SR 16', picture: './weapons/sr-16.png' },
  { id: 'supernova', name: 'Supernova', picture: './weapons/supernova.png' },
  { id: 'tle_1911', name: 'TLE 1911', picture: './weapons/tle_1911.png' },
  { id: 'tpl', name: 'TPL', picture: './weapons/tpl.png' },
  { id: 'trpl', name: 'TRPL', picture: './weapons/trpl.png' },
  { id: 'ump-9', name: 'UMP 9', picture: './weapons/ump-9.png' },
  { id: 'ump-45', name: 'UMP 45', picture: './weapons/ump-45.png' },
  { id: 'usp45', name: 'USP45', picture: './weapons/usp45.png' },
  { id: 'vpl-25', name: 'VPL 25', picture: './weapons/vpl-25.png' }
];
